server:
  port: 18080

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/HP/Desktop/Sparta/springcloud/com.spring-cloud.eureka.client.config/src/main/resources/config-repo
    bus:
      destination: springCloudBus
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: busrefresh  #refresh /bus/refresh ?????? ????? POST ??? ??